### ISSUE TITLE
Days.get(0) returns undefined

### ISSUE THREAD

**Issue by NickBusey** [zeroasterisk/meteor-super-enums#1]
Console Output:

var Days = SEnum([
  "Sunday",
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday"
]);

Days.get(0)
undefined
Days.get(1)
Object {value: 1, label: "Monday", key: "monday"}
Days[0]
Object {value: 0, label: "Sunday", key: "sunday"}
Days[1]
Object {value: 1, label: "Monday", key: "monday"}

As you can see, Days.get(0) does not work as expected.

**Comment by zeroasterisk** [comment]
@NickBusey let me know if this is now good for you.  thanks for trying this out.  we are using this package and it's working well for us, hope it's good for you too.

**Comment by NickBusey** [comment]
Looks like the new version hasn't made it up to Atmosphere yet, as soon as it's available I'll try it out. Thanks very much for putting this package together, definitely very useful. (In fact so many people are probably NOT using Enums who should be that this should probably just be part of Meteor core and how they show 'status' etc in the Demo apps.

**Comment by zeroasterisk** [comment]
So sorry - I forgot to publish the new version within meteor.  should now be available.  thanks!

**Comment by zeroasterisk** [comment]
Also - I agree - enums are sadly absent in most of the Meteor world.  They make a LOT of sense, and Meteor makes them so easy to use... it's just sad it's not more common -- thanks for taking a look and helping out!

**Comment by NickBusey** [comment]
Working great now!
